import Wiyorent from '../../assets/wiyorent.jpg';
import Hair from '../../assets/braids.jpg';
import Krossty from '../../assets/krossty.jpg';
import Qrcode from '../../assets/qrcode.png';
import CMC from '../../assets/cmc.jpg';
import Fundatrade from '../../assets/fundatrade.png';
import RememberMe from '../../assets/rememberme.png';
import quotes from '../../assets/quotes.png';
import beeDashboard from '../../assets/dasboard_bee.png';
import portfolio from '../../assets/portfolio.png';
import shop from '../../assets/shop.png';
import shadowescape from '../../assets/shadowescape.png';

/*
  Données projets — vérifiées sur les dépôts GitHub (juillet 2026).
  `featured` place le projet en tête de grille.
  `github: null` = dépôt privé (aucun lien public possible).
*/

export const projectsData = [
  // ── Projets en vedette ──────────────────────────────────────────────
  {
    id: 1,
    image: beeDashboard,
    title: 'Allibuy',
    category: 'Full-Stack',
    status: 'En développement',
    featured: true,
    link: null,
    github: null,
    desc: "Marketplace e-commerce internationale multi-vendeurs en monorepo (web, mobile, API) : multi-devises, quatre rôles, paiements mobile money, recherche Meilisearch, temps réel Socket.io, sécurité PostgreSQL avancée (RLS, triggers). Dépôt privé.",
    tech: ['Next.js 15', 'React 19', 'NestJS', 'Prisma', 'PostgreSQL', 'Redis / BullMQ', 'Meilisearch', 'Expo (React Native)', 'Docker'],
  },
  {
    id: 2,
    image: null,
    title: 'Zolya',
    category: 'Full-Stack',
    status: 'En développement',
    featured: true,
    link: null,
    github: null,
    desc: "Marketplace C2C avec logistique de livraison intégrée : API NestJS sécurisée (Argon2id, RBAC, escrow et registre financier en double entrée), files Redis / BullMQ, application mobile Flutter (Clean Architecture + BLoC), tests unitaires et documentation. Dépôt privé.",
    tech: ['Flutter', 'NestJS', 'PostgreSQL / Prisma', 'Redis / BullMQ', 'Swagger', 'Docker'],
  },
  {
    id: 3,
    image: null,
    title: 'NexaGold',
    category: 'Data & IA',
    status: 'En développement',
    featured: true,
    link: null,
    github: null,
    desc: "Plateforme de trading algorithmique sur l'or pilotée par IA : moteur Python FastAPI (données → stratégie → risque → exécution) connecté à un broker par API, modèles gradient boosting (LightGBM), backtesting sur historique profond, kill switch de sécurité, API NestJS et dashboard Next.js. Dépôt privé.",
    tech: ['Python (FastAPI)', 'scikit-learn / LightGBM', 'pandas', 'NestJS', 'Next.js', 'PostgreSQL', 'Redis'],
  },
  {
    id: 4,
    image: null,
    title: 'Cyna',
    category: 'Full-Stack',
    status: 'Déployé · académique, en équipe',
    featured: true,
    link: 'https://cynaapp.vercel.app',
    github: 'https://github.com/Nagoloum/Frontend_cyna',
    desc: "Plateforme SaaS de cybersécurité réalisée en équipe (INGETIS) : front React 19 avec Redux Toolkit, paiement Stripe, multilingue FR/EN et tableaux de bord ; API NestJS + MongoDB avec JWT, rate limiting et documentation Swagger.",
    tech: ['React 19', 'Redux Toolkit', 'Stripe', 'i18next', 'NestJS', 'MongoDB', 'Swagger'],
  },
  {
    id: 5,
    image: Fundatrade,
    title: 'Fundatrade',
    category: 'Data & IA',
    status: 'Déployé',
    featured: true,
    link: 'https://fundatrade.vercel.app/',
    github: 'https://github.com/Nagoloum/Fundatrade',
    desc: "Plateforme d'analyse fondamentale et technique du Bitcoin et de l'Or : prix en temps réel (WebSocket Kraken), 8 indicateurs techniques calculés côté serveur, 6 stratégies croisées via un système de scoring et suivi de la performance des prédictions.",
    tech: ['Next.js 15', 'React 19', 'TypeScript', 'Recharts', 'WebSockets', 'Vercel'],
  },
  {
    id: 6,
    image: null,
    title: 'Thebarber',
    category: 'Full-Stack',
    status: 'Déployé',
    featured: true,
    link: 'https://thebarber-ten.vercel.app',
    github: 'https://github.com/Nagoloum/Thebarber',
    desc: "Site de salon de coiffure avec réservation en ligne et back-office : logique métier séparée, validation des formulaires (Zod, React Hook Form), authentification NextAuth et socle RGPD / CNIL.",
    tech: ['Next.js', 'TypeScript', 'Prisma', 'PostgreSQL', 'NextAuth', 'Zod'],
  },

  // ── Autres projets ──────────────────────────────────────────────────
  {
    id: 7,
    image: null,
    title: 'Findit',
    category: 'Full-Stack',
    status: 'En développement',
    link: null,
    github: null,
    desc: "Agrégateur d'offres d'alternance et de stage en Île-de-France avec score de compatibilité CV-offre explicable : monorepo web / API / worker (BullMQ), périmètre métier centralisé et garde-fous de conformité. Dépôt privé.",
    tech: ['Next.js', 'NestJS + Fastify', 'PostgreSQL', 'BullMQ', 'Docker', 'pnpm / Turborepo'],
  },
  {
    id: 8,
    image: null,
    title: 'XAUFxBot',
    category: 'Data & IA',
    status: 'Fonctionnel',
    link: 'https://github.com/Nagoloum/XAUFxBot',
    github: 'https://github.com/Nagoloum/XAUFxBot',
    desc: "Bot de trading automatisé spécialisé sur l'or (XAU/USD) via MetaTrader 5 : analyse de volatilité, gestion du risque, alertes Telegram et tableau de bord Streamlit.",
    tech: ['Python', 'MetaTrader5', 'pandas / NumPy', 'MongoDB', 'Streamlit', 'Telegram API'],
  },
  {
    id: 9,
    image: null,
    title: 'SYNFxBot',
    category: 'Data & IA',
    status: 'Fonctionnel',
    link: 'https://github.com/Nagoloum/SYNFxBot',
    github: 'https://github.com/Nagoloum/SYNFxBot',
    desc: "Bot de trading automatisé pour les indices synthétiques : stratégie de confirmation de structure pour trader les mouvements explosifs avec gestion de risque avancée.",
    tech: ['Python', 'MetaTrader5', 'pandas', 'MongoDB', 'Streamlit', 'Telegram API'],
  },
  {
    id: 11,
    image: null,
    title: 'NagosUI',
    category: 'Front-End',
    status: 'En développement',
    link: 'https://nagosui.vercel.app',
    github: 'https://github.com/Nagoloum/NagosUI',
    desc: "Librairie de composants front-end animés et fluides, accompagnée de sites de démonstration cinématiques ; monorepo pnpm + Turborepo.",
    tech: ['Next.js 16', 'React 19', 'TypeScript', 'Tailwind CSS v4', 'Turborepo'],
  },
  {
    id: 12,
    image: RememberMe,
    title: 'RememberMe',
    category: 'Full-Stack',
    status: 'Déployé',
    link: 'https://rememberme-lemon-chi.vercel.app/',
    github: 'https://github.com/Nagoloum/Backend_RememberMe',
    desc: "Application de planification de tâches : API REST Node.js / Express / MongoDB avec authentification JWT et architecture MVC, consommée par un front React déployé.",
    tech: ['React', 'Node.js', 'Express', 'MongoDB', 'JWT', 'Vercel'],
  },
  {
    id: 13,
    image: null,
    title: 'Task App',
    category: 'Full-Stack',
    status: 'Terminé',
    link: null,
    github: 'https://github.com/Nagoloum/libheros-task-app',
    desc: "Clone de Wunderlist / Google Tasks : front Angular 18 (formulaires réactifs, RxJS) et API NestJS avec authentification JWT.",
    tech: ['Angular 18', 'NestJS', 'TypeScript', 'Tailwind CSS'],
  },
  {
    id: 14,
    image: Wiyorent,
    title: 'Wiyorent',
    category: 'Front-End',
    status: 'Déployé',
    link: 'https://Wiyorent.vercel.app/',
    github: 'https://github.com/Nagoloum/wiyorent',
    desc: 'Plateforme vitrine de location et réservation en ligne — recherche avancée, fiches propriétés et système de réservation.',
    tech: ['React', 'i18next', 'API WhatsApp', 'Vercel'],
  },
  {
    id: 15,
    image: Hair,
    title: 'Irene Hair Braids',
    category: 'Front-End',
    status: 'Déployé',
    link: 'https://irene-hair-braids.vercel.app/',
    github: 'https://github.com/Nagoloum/irene-hair-braids',
    desc: 'Site de prise de rendez-vous pour un salon de coiffure — design moderne, formulaire de contact.',
    tech: ['React', 'i18next', 'Vercel'],
  },
  {
    id: 16,
    image: Krossty,
    title: 'Krossty',
    category: 'Front-End',
    status: 'Déployé',
    link: 'https://krossty-chips.com/',
    github: 'https://github.com/Nagoloum/Krossty',
    desc: 'Site de vente de chips — vitrine produits, panier et contact via WhatsApp, domaine personnalisé.',
    tech: ['React', 'API WhatsApp', 'Vercel'],
  },
  {
    id: 17,
    image: CMC,
    title: 'Creamy Milk Candies',
    category: 'Front-End',
    status: 'Déployé',
    link: 'https://creamy-milk-candies.vercel.app/',
    github: 'https://github.com/Nagoloum/Creamy-milk-candies',
    desc: 'Site de vente de bonbons premium — galerie produits et contact via WhatsApp.',
    tech: ['React', 'i18next', 'EmailJS', 'Vercel'],
  },
  {
    id: 18,
    image: Qrcode,
    title: 'QR Studio Ad',
    category: 'Front-End',
    status: 'Déployé',
    link: 'https://qrstudio-lovat.vercel.app/',
    github: 'https://github.com/Nagoloum/QrStudioAd',
    desc: "Générateur de codes QR personnalisés — création et export au format image, interface multilingue.",
    tech: ['React', 'react-qr-code', 'i18next', 'Vercel'],
  },
  {
    id: 19,
    image: null,
    title: 'Urbanet',
    category: 'Front-End',
    status: 'Déployé',
    link: 'https://urbanet-two.vercel.app',
    github: 'https://github.com/Nagoloum/Urbanet',
    desc: 'Site vitrine animé — navigation fluide et animations Framer Motion.',
    tech: ['React', 'TypeScript', 'Framer Motion', 'Vercel'],
  },
  {
    id: 20,
    image: portfolio,
    title: 'Mon Portfolio',
    category: 'Front-End',
    status: 'En production',
    link: 'https://nagoloum.vercel.app',
    github: 'https://github.com/Nagoloum/Nagos',
    desc: 'Ce portfolio : sphère de particules 3D, animations au défilement, thème clair/sombre persistant, blog et formulaire de contact.',
    tech: ['React 19', 'Vite', 'GSAP', 'Three.js (R3F)', 'Swiper', 'EmailJS'],
  },
  {
    id: 21,
    image: null,
    title: 'SellCatalog',
    category: 'Mobile',
    status: 'Prototype fonctionnel',
    link: null,
    github: 'https://github.com/Nagoloum/SellCatalog',
    desc: "Application mobile Flutter avec API Python Flask : connexion, catalogue de ventes privées, recherche, filtres par catégorie et favoris persistants.",
    tech: ['Flutter', 'Dart', 'Python (Flask)'],
  },
  {
    id: 22,
    image: null,
    title: 'Basic Shop App',
    category: 'Mobile',
    status: 'En développement',
    link: null,
    github: 'https://github.com/Nagoloum/Basic-shop-app',
    desc: "Application boutique Android en Kotlin — projet d'apprentissage du développement mobile natif.",
    tech: ['Kotlin', 'Android'],
  },
  {
    id: 23,
    image: shadowescape,
    title: 'Shadow Escape',
    category: 'Jeu',
    status: 'Prototype',
    link: null,
    github: 'https://github.com/Nagoloum/Shadow_Escape',
    desc: "Jeu d'infiltration Unity : cônes de vision ennemis, zones d'ombre définies par shaders custom (ShaderLab).",
    tech: ['Unity', 'C#', 'ShaderLab'],
  },
  {
    id: 24,
    image: shop,
    title: 'Shop App',
    category: 'Full-Stack',
    status: 'Projet académique',
    link: null,
    github: 'https://github.com/Nagoloum/Springboot_project',
    desc: 'Mini application e-commerce : back-end Java Spring Boot et front Vue.js.',
    tech: ['Java', 'Spring Boot', 'Vue.js'],
  },
  {
    id: 25,
    image: quotes,
    title: 'Quotes',
    category: 'Front-End',
    status: 'Déployé',
    link: 'https://projet-citations-dusky.vercel.app/',
    github: 'https://github.com/Nagoloum/projet-citations',
    desc: 'Générateur de citations aléatoires — exercice JavaScript vanilla.',
    tech: ['HTML5', 'CSS3', 'JavaScript'],
  },
  {
    id: 26,
    image: null,
    title: 'Gestion Tickets Bus',
    category: 'Full-Stack',
    status: 'Projet académique',
    link: null,
    github: 'https://github.com/Nagoloum/Gestion_tickets_bus',
    desc: 'Système de réservation de tickets de bus : sessions, rôles et CRUD complet en PHP / MySQL.',
    tech: ['PHP', 'MySQL', 'JavaScript', 'SCSS'],
  },
  {
    id: 27,
    image: null,
    title: 'Feedback',
    category: 'Full-Stack',
    status: 'Projet académique',
    link: null,
    github: 'https://github.com/Nagoloum/Feedback',
    desc: 'Système de collecte de retours utilisateurs en PHP.',
    tech: ['PHP', 'JavaScript', 'SCSS'],
  },
];

export const projectsNav = [
  { name: 'Tous' },
  { name: 'Full-Stack' },
  { name: 'Front-End' },
  { name: 'Data & IA' },
  { name: 'Mobile' },
  { name: 'Jeu' },
];
